-- Enable necessary extensions
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- Create Events table
CREATE TABLE IF NOT EXISTS events (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title TEXT NOT NULL,
  description TEXT NOT NULL,
  date TIMESTAMP WITH TIME ZONE NOT NULL,
  location TEXT NOT NULL,
  category TEXT NOT NULL,
  image_url TEXT NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Create Ticket Types table
CREATE TABLE IF NOT EXISTS ticket_types (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  price NUMERIC NOT NULL,
  stock INTEGER NOT NULL,
  event_id BIGINT REFERENCES events(id) ON DELETE CASCADE
);

-- Create Reservations table
CREATE TABLE IF NOT EXISTS reservations (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  customer_name TEXT NOT NULL,
  customer_email TEXT NOT NULL,
  quantity INTEGER NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  ticket_type_id BIGINT REFERENCES ticket_types(id)
);

-- Function to handle atomic reservations
CREATE OR REPLACE FUNCTION make_reservation(
  p_ticket_type_id BIGINT,
  p_customer_name TEXT,
  p_customer_email TEXT,
  p_quantity INTEGER
)
RETURNS JSON
LANGUAGE plpgsql
AS $$
DECLARE
  v_stock INTEGER;
  v_reservation_id BIGINT;
BEGIN
  -- Check stock with lock (atomic)
  SELECT stock INTO v_stock FROM ticket_types WHERE id = p_ticket_type_id FOR UPDATE;
  
  IF v_stock IS NULL THEN
    RAISE EXCEPTION 'Ticket type not found';
  END IF;
  
  IF v_stock < p_quantity THEN
    RAISE EXCEPTION 'Not enough stock';
  END IF;
  
  -- Decrement stock
  UPDATE ticket_types SET stock = stock - p_quantity WHERE id = p_ticket_type_id;
  
  -- Create reservation
  INSERT INTO reservations (ticket_type_id, customer_name, customer_email, quantity)
  VALUES (p_ticket_type_id, p_customer_name, p_customer_email, p_quantity)
  RETURNING id INTO v_reservation_id;
  
  RETURN json_build_object('id', v_reservation_id, 'status', 'success');
END;
$$;

-- Seed Data (Optional)
INSERT INTO events (title, description, date, location, category, image_url)
VALUES 
  ('Gran Partido: Real Madrid vs Barcelona', 'El clásico del fútbol español.', '2024-05-20 20:00:00+00', 'Estadio Santiago Bernabéu', 'Fútbol', 'https://images.unsplash.com/photo-1579952363873-27f3bde9be2b?ixlib=rb-1.2.1&auto=format&fit=crop&w=1350&q=80'),
  ('Concierto de Rock: The Rolling Stones', 'La legendaria banda en vivo.', '2024-06-15 21:00:00+00', 'Estadio Wembley', 'Recital', 'https://images.unsplash.com/photo-1501612780327-45045538702b?ixlib=rb-1.2.1&auto=format&fit=crop&w=1350&q=80'),
  ('Obra de Teatro: Hamlet', 'La tragedia de Shakespeare.', '2024-07-10 19:00:00+00', 'Teatro Real', 'Teatro', 'https://images.unsplash.com/photo-1507924538820-ede94a04019d?ixlib=rb-1.2.1&auto=format&fit=crop&w=1350&q=80');

INSERT INTO ticket_types (name, price, stock, event_id)
VALUES
  ('VIP', 150.0, 100, 1),
  ('General', 50.0, 5000, 1),
  ('Front Stage', 200.0, 50, 2),
  ('General', 80.0, 2000, 2),
  ('Palco', 100.0, 20, 3),
  ('Patio de Butacas', 40.0, 300, 3);
