-- Create Events table
CREATE TABLE IF NOT EXISTS events (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title TEXT NOT NULL,
  description TEXT NOT NULL,
  date TIMESTAMP WITH TIME ZONE NOT NULL,
  location TEXT NOT NULL,
  category TEXT NOT NULL,
  image_url TEXT NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Create Ticket Types table
CREATE TABLE IF NOT EXISTS ticket_types (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  price NUMERIC NOT NULL,
  stock INTEGER NOT NULL,
  event_id BIGINT REFERENCES events(id) ON DELETE CASCADE
);

-- Create Reservations table
CREATE TABLE IF NOT EXISTS reservations (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  customer_name TEXT NOT NULL,
  customer_email TEXT NOT NULL,
  quantity INTEGER NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  ticket_type_id BIGINT REFERENCES ticket_types(id)
);

-- Insert Seed Data
INSERT INTO events (title, description, date, location, category, image_url)
VALUES 
  ('Gran Partido: Real Madrid vs Barcelona', 'El clásico del fútbol español.', '2024-05-20 20:00:00+00', 'Estadio Santiago Bernabéu', 'Fútbol', 'https://images.unsplash.com/photo-1579952363873-27f3bde9be2b?ixlib=rb-1.2.1&auto=format&fit=crop&w=1350&q=80'),
  ('Concierto de Rock: The Rolling Stones', 'La legendaria banda en vivo.', '2024-06-15 21:00:00+00', 'Estadio Wembley', 'Recital', 'https://images.unsplash.com/photo-1501612780327-45045538702b?ixlib=rb-1.2.1&auto=format&fit=crop&w=1350&q=80'),
  ('Obra de Teatro: Hamlet', 'La tragedia de Shakespeare.', '2024-07-10 19:00:00+00', 'Teatro Real', 'Teatro', 'https://images.unsplash.com/photo-1507924538820-ede94a04019d?ixlib=rb-1.2.1&auto=format&fit=crop&w=1350&q=80');

-- Insert Ticket Types (Need to fetch event IDs dynamically in real scenario, but assuming sequential IDs for seed)
-- Assuming IDs 1, 2, 3 generated above
INSERT INTO ticket_types (name, price, stock, event_id)
VALUES
  ('VIP', 150.0, 100, 1),
  ('General', 50.0, 5000, 1),
  ('Front Stage', 200.0, 50, 2),
  ('General', 80.0, 2000, 2),
  ('Palco', 100.0, 20, 3),
  ('Patio de Butacas', 40.0, 300, 3);
