-- Create payment_settings table
CREATE TABLE IF NOT EXISTS payment_settings (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  bank_name TEXT NOT NULL,
  account_holder TEXT NOT NULL,
  cbu TEXT NOT NULL,
  alias TEXT NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Insert default payment settings (placeholder)
INSERT INTO payment_settings (bank_name, account_holder, cbu, alias)
VALUES ('Banco Galicia', 'GoVip Eventos S.A.', '0070123400000012345678', 'GOVIP.EVENTOS.PAGO')
ON CONFLICT DO NOTHING;

-- Disable RLS for public read access (or add policy)
ALTER TABLE payment_settings ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow public read access" ON payment_settings
  FOR SELECT USING (true);

CREATE POLICY "Allow admin write access" ON payment_settings
  FOR ALL USING (true); -- Simplified for now, usually restricted to admin role
